"""Type stubs for booster_sdk_bindings."""

from __future__ import annotations

BOOSTER_ROBOT_USER_ID: str

class BoosterSdkError(Exception):
    """Exception raised by the Booster SDK."""

    ...

class RobotMode:
    UNKNOWN: RobotMode
    DAMPING: RobotMode
    PREPARE: RobotMode
    WALKING: RobotMode
    CUSTOM: RobotMode
    SOCCER: RobotMode

    def __repr__(self) -> str: ...
    def __int__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...

class Hand:
    LEFT: Hand
    RIGHT: Hand

    def __repr__(self) -> str: ...
    def __int__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...

class GripperMode:
    POSITION: GripperMode
    FORCE: GripperMode

    def __repr__(self) -> str: ...
    def __int__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...

class HandAction:
    OPEN: HandAction
    CLOSE: HandAction

    def __repr__(self) -> str: ...
    def __int__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...

class Frame:
    UNKNOWN: Frame
    BODY: Frame
    HEAD: Frame
    LEFT_HAND: Frame
    RIGHT_HAND: Frame
    LEFT_FOOT: Frame
    RIGHT_FOOT: Frame

    def __repr__(self) -> str: ...
    def __int__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...

class GripperControlMode:
    POSITION: GripperControlMode
    FORCE: GripperControlMode

    def __repr__(self) -> str: ...
    def __int__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...

class BoosterHandType:
    INSPIRE_HAND: BoosterHandType
    INSPIRE_TOUCH_HAND: BoosterHandType
    REVO_HAND: BoosterHandType
    UNKNOWN: BoosterHandType

    def __repr__(self) -> str: ...
    def __int__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...

class DanceId:
    NEW_YEAR: DanceId
    NEZHA: DanceId
    TOWARDS_FUTURE: DanceId
    DABBING_GESTURE: DanceId
    ULTRAMAN_GESTURE: DanceId
    RESPECT_GESTURE: DanceId
    CHEERING_GESTURE: DanceId
    LUCKY_CAT_GESTURE: DanceId
    STOP: DanceId

    def __repr__(self) -> str: ...
    def __int__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...

class WholeBodyDanceId:
    ARBIC_DANCE: WholeBodyDanceId
    MICHAEL_DANCE_1: WholeBodyDanceId
    MICHAEL_DANCE_2: WholeBodyDanceId
    MICHAEL_DANCE_3: WholeBodyDanceId
    MOON_WALK: WholeBodyDanceId
    BOXING_STYLE_KICK: WholeBodyDanceId
    ROUNDHOUSE_KICK: WholeBodyDanceId

    def __repr__(self) -> str: ...
    def __int__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...

class JointOrder:
    MUJOCO: JointOrder
    ISAAC_LAB: JointOrder

    def __repr__(self) -> str: ...
    def __int__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...

class BodyControl:
    UNKNOWN: BodyControl
    DAMPING: BodyControl
    PREPARE: BodyControl
    HUMANLIKE_GAIT: BodyControl
    PRONE_BODY: BodyControl
    SOCCER_GAIT: BodyControl
    CUSTOM: BodyControl
    GET_UP: BodyControl
    WHOLE_BODY_DANCE: BodyControl
    SHOOT: BodyControl
    INSIDE_FOOT: BodyControl
    GOALIE: BodyControl
    WBC_GAIT: BodyControl

    def __repr__(self) -> str: ...
    def __int__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...

class Action:
    UNKNOWN: Action
    HAND_SHAKE: Action
    HAND_WAVE: Action
    HAND_CONTROL: Action
    DANCE_NEW_YEAR: Action
    DANCE_NEZHA: Action
    DANCE_TOWARDS_FUTURE: Action
    GESTURE_DABBING: Action
    GESTURE_ULTRAMAN: Action
    GESTURE_RESPECT: Action
    GESTURE_CHEER: Action
    GESTURE_LUCKY_CAT: Action
    GESTURE_BOXING: Action
    ZERO_TORQUE_DRAG: Action
    RECORD_TRAJ: Action
    RUN_RECORDED_TRAJ: Action

    def __repr__(self) -> str: ...
    def __int__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...

class CameraSetMode:
    CAMERA_MODE_NORMAL: CameraSetMode
    CAMERA_MODE_HIGH_RESOLUTION: CameraSetMode
    CAMERA_MODE_NORMAL_ENABLE: CameraSetMode
    CAMERA_MODE_HIGH_RESOLUTION_ENABLE: CameraSetMode

    def __repr__(self) -> str: ...
    def __int__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...

class CameraControlStatus:
    CAMERA_STATUS_NORMAL: CameraControlStatus
    CAMERA_STATUS_HIGH_RESOLUTION: CameraControlStatus
    CAMERA_STATUS_ERROR: CameraControlStatus
    CAMERA_STATUS_NULL: CameraControlStatus

    def __repr__(self) -> str: ...
    def __int__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...

class GripperCommand:
    def __init__(
        self,
        hand: Hand,
        mode: GripperMode,
        motion_param: int,
        speed: int | None = ...,
    ) -> None: ...
    @staticmethod
    def open(hand: Hand) -> GripperCommand: ...
    @staticmethod
    def close(hand: Hand) -> GripperCommand: ...
    @staticmethod
    def grasp(hand: Hand, force: int) -> GripperCommand: ...
    @property
    def hand(self) -> Hand: ...
    @property
    def mode(self) -> GripperMode: ...
    @property
    def motion_param(self) -> int: ...
    @property
    def speed(self) -> int: ...
    def __repr__(self) -> str: ...

class Position:
    def __init__(self, x: float, y: float, z: float) -> None: ...
    @property
    def x(self) -> float: ...
    @x.setter
    def x(self, value: float) -> None: ...
    @property
    def y(self) -> float: ...
    @y.setter
    def y(self, value: float) -> None: ...
    @property
    def z(self) -> float: ...
    @z.setter
    def z(self, value: float) -> None: ...

class Orientation:
    def __init__(self, roll: float, pitch: float, yaw: float) -> None: ...
    @property
    def roll(self) -> float: ...
    @roll.setter
    def roll(self, value: float) -> None: ...
    @property
    def pitch(self) -> float: ...
    @pitch.setter
    def pitch(self, value: float) -> None: ...
    @property
    def yaw(self) -> float: ...
    @yaw.setter
    def yaw(self, value: float) -> None: ...

class Posture:
    def __init__(self, position: Position, orientation: Orientation) -> None: ...
    @property
    def position(self) -> Position: ...
    @position.setter
    def position(self, value: Position) -> None: ...
    @property
    def orientation(self) -> Orientation: ...
    @orientation.setter
    def orientation(self, value: Orientation) -> None: ...

class Quaternion:
    def __init__(self, x: float, y: float, z: float, w: float) -> None: ...
    @property
    def x(self) -> float: ...
    @property
    def y(self) -> float: ...
    @property
    def z(self) -> float: ...
    @property
    def w(self) -> float: ...

class Transform:
    def __init__(self, position: Position, orientation: Quaternion) -> None: ...
    @property
    def position(self) -> Position: ...
    @property
    def orientation(self) -> Quaternion: ...

class GripperMotionParameter:
    def __init__(self, position: int, force: int, speed: int) -> None: ...
    @property
    def position(self) -> int: ...
    @property
    def force(self) -> int: ...
    @property
    def speed(self) -> int: ...

class DexterousFingerParameter:
    def __init__(self, seq: int, angle: int, force: int, speed: int) -> None: ...
    @property
    def seq(self) -> int: ...
    @property
    def angle(self) -> int: ...
    @property
    def force(self) -> int: ...
    @property
    def speed(self) -> int: ...

class CustomModelParams:
    def __init__(
        self, action_scale: list[float], kp: list[float], kd: list[float]
    ) -> None: ...
    @property
    def action_scale(self) -> list[float]: ...
    @property
    def kp(self) -> list[float]: ...
    @property
    def kd(self) -> list[float]: ...

class CustomModel:
    def __init__(
        self,
        file_path: str,
        params: list[CustomModelParams],
        joint_order: JointOrder,
    ) -> None: ...
    @property
    def file_path(self) -> str: ...
    @property
    def params(self) -> list[CustomModelParams]: ...
    @property
    def joint_order(self) -> JointOrder: ...

class CustomTrainedTraj:
    def __init__(self, traj_file_path: str, model: CustomModel) -> None: ...
    @property
    def traj_file_path(self) -> str: ...
    @property
    def model(self) -> CustomModel: ...

class TtsConfig:
    def __init__(self, voice_type: str, ignore_bracket_text: list[int]) -> None: ...
    @property
    def voice_type(self) -> str: ...
    @property
    def ignore_bracket_text(self) -> list[int]: ...

class LlmConfig:
    def __init__(
        self, system_prompt: str, welcome_msg: str, prompt_name: str
    ) -> None: ...
    @property
    def system_prompt(self) -> str: ...
    @property
    def welcome_msg(self) -> str: ...
    @property
    def prompt_name(self) -> str: ...

class AsrConfig:
    def __init__(
        self, interrupt_speech_duration: int, interrupt_keywords: list[str]
    ) -> None: ...
    @property
    def interrupt_speech_duration(self) -> int: ...
    @property
    def interrupt_keywords(self) -> list[str]: ...

class StartAiChatParameter:
    def __init__(
        self,
        interrupt_mode: bool,
        asr_config: AsrConfig,
        llm_config: LlmConfig,
        tts_config: TtsConfig,
        enable_face_tracking: bool,
    ) -> None: ...
    @property
    def interrupt_mode(self) -> bool: ...
    @property
    def asr_config(self) -> AsrConfig: ...
    @property
    def llm_config(self) -> LlmConfig: ...
    @property
    def tts_config(self) -> TtsConfig: ...
    @property
    def enable_face_tracking(self) -> bool: ...

class SpeakParameter:
    def __init__(self, msg: str) -> None: ...
    @property
    def msg(self) -> str: ...

class LuiTtsConfig:
    def __init__(self, voice_type: str) -> None: ...
    @property
    def voice_type(self) -> str: ...

class LuiTtsParameter:
    def __init__(self, text: str) -> None: ...
    @property
    def text(self) -> str: ...

class GetModeResponse:
    def __init__(self, mode: int) -> None: ...
    @property
    def mode(self) -> int: ...
    def mode_enum(self) -> RobotMode | None: ...

class GetStatusResponse:
    def __init__(
        self,
        current_mode: int,
        current_body_control: int,
        current_actions: list[int],
    ) -> None: ...
    @property
    def current_mode(self) -> int: ...
    @property
    def current_body_control(self) -> int: ...
    @property
    def current_actions(self) -> list[int]: ...
    def current_mode_enum(self) -> RobotMode | None: ...
    def current_body_control_enum(self) -> BodyControl | None: ...
    def current_actions_enum(self) -> list[Action]: ...

class GetRobotInfoResponse:
    def __init__(
        self,
        name: str,
        nickname: str,
        version: str,
        model: str,
        serial_number: str,
    ) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def nickname(self) -> str: ...
    @property
    def version(self) -> str: ...
    @property
    def model(self) -> str: ...
    @property
    def serial_number(self) -> str: ...

class LoadCustomTrainedTrajResponse:
    def __init__(self, tid: str) -> None: ...
    @property
    def tid(self) -> str: ...

class X5CameraGetStatusResponse:
    def __init__(self, status: int) -> None: ...
    @property
    def status(self) -> int: ...
    def status_enum(self) -> CameraControlStatus | None: ...

class DetectResults:
    def __init__(
        self,
        xmin: int,
        ymin: int,
        xmax: int,
        ymax: int,
        position: list[float],
        tag: str,
        conf: float,
        rgb_mean: list[int],
    ) -> None: ...
    @property
    def xmin(self) -> int: ...
    @property
    def ymin(self) -> int: ...
    @property
    def xmax(self) -> int: ...
    @property
    def ymax(self) -> int: ...
    @property
    def position(self) -> list[float]: ...
    @property
    def tag(self) -> str: ...
    @property
    def conf(self) -> float: ...
    @property
    def rgb_mean(self) -> list[int]: ...

class BoosterClient:
    def __init__(self) -> None: ...
    def change_mode(self, mode: RobotMode) -> None: ...
    def get_mode(self) -> GetModeResponse: ...
    def get_status(self) -> GetStatusResponse: ...
    def get_robot_info(self) -> GetRobotInfoResponse: ...
    def move_robot(self, vx: float, vy: float, vyaw: float) -> None: ...
    def rotate_head(self, pitch: float, yaw: float) -> None: ...
    def wave_hand(self, action: HandAction) -> None: ...
    def rotate_head_with_direction(
        self, pitch_direction: int, yaw_direction: int
    ) -> None: ...
    def lie_down(self) -> None: ...
    def get_up(self) -> None: ...
    def get_up_with_mode(self, mode: RobotMode) -> None: ...
    def shoot(self) -> None: ...
    def push_up(self) -> None: ...
    def move_hand_end_effector(
        self,
        target_posture: Posture,
        time_millis: int,
        hand_index: Hand,
    ) -> None: ...
    def move_hand_end_effector_with_aux(
        self,
        target_posture: Posture,
        aux_posture: Posture,
        time_millis: int,
        hand_index: Hand,
    ) -> None: ...
    def move_hand_end_effector_v2(
        self,
        target_posture: Posture,
        time_millis: int,
        hand_index: Hand,
    ) -> None: ...
    def stop_hand_end_effector(self) -> None: ...
    def control_gripper(
        self,
        motion_param: GripperMotionParameter,
        mode: GripperControlMode,
        hand_index: Hand,
    ) -> None: ...
    def get_frame_transform(self, src: Frame, dst: Frame) -> Transform: ...
    def switch_hand_end_effector_control_mode(self, switch_on: bool) -> None: ...
    def handshake(self, action: HandAction) -> None: ...
    def control_dexterous_hand(
        self,
        finger_params: list[DexterousFingerParameter],
        hand_index: Hand,
        hand_type: BoosterHandType,
    ) -> None: ...
    def control_dexterous_hand_default(
        self,
        finger_params: list[DexterousFingerParameter],
        hand_index: Hand,
    ) -> None: ...
    def dance(self, dance_id: DanceId) -> None: ...
    def play_sound(self, sound_file_path: str) -> None: ...
    def stop_sound(self) -> None: ...
    def zero_torque_drag(self, active: bool) -> None: ...
    def record_trajectory(self, active: bool) -> None: ...
    def replay_trajectory(self, traj_file_path: str) -> None: ...
    def whole_body_dance(self, dance_id: WholeBodyDanceId) -> None: ...
    def upper_body_custom_control(self, start: bool) -> None: ...
    def reset_odometry(self) -> None: ...
    def load_custom_trained_traj(
        self,
        traj: CustomTrainedTraj,
    ) -> LoadCustomTrainedTrajResponse: ...
    def activate_custom_trained_traj(self, tid: str) -> None: ...
    def unload_custom_trained_traj(self, tid: str) -> None: ...
    def enter_wbc_gait(self) -> None: ...
    def exit_wbc_gait(self) -> None: ...
    def publish_gripper_command(self, command: GripperCommand) -> None: ...
    def publish_gripper(
        self,
        hand: Hand,
        mode: GripperMode,
        motion_param: int,
        speed: int | None = ...,
    ) -> None: ...

class AiClient:
    def __init__(self) -> None: ...
    def start_ai_chat(self, param: StartAiChatParameter) -> None: ...
    def stop_ai_chat(self) -> None: ...
    def speak(self, param: SpeakParameter) -> None: ...
    def start_face_tracking(self) -> None: ...
    def stop_face_tracking(self) -> None: ...

class LuiClient:
    def __init__(self) -> None: ...
    def start_asr(self) -> None: ...
    def stop_asr(self) -> None: ...
    def start_tts(self, config: LuiTtsConfig) -> None: ...
    def stop_tts(self) -> None: ...
    def send_tts_text(self, param: LuiTtsParameter) -> None: ...

class LightControlClient:
    def __init__(self) -> None: ...
    def set_led_light_color(self, r: int, g: int, b: int) -> None: ...
    def stop_led_light_control(self) -> None: ...

class VisionClient:
    def __init__(self) -> None: ...
    def start_vision_service(
        self,
        enable_position: bool,
        enable_color: bool,
        enable_face_detection: bool,
    ) -> None: ...
    def stop_vision_service(self) -> None: ...
    def get_detection_object_with_ratio(
        self, focus_ratio: float
    ) -> list[DetectResults]: ...
    def get_detection_object(self) -> list[DetectResults]: ...

class X5CameraClient:
    def __init__(self) -> None: ...
    def change_mode(self, mode: CameraSetMode) -> None: ...
    def get_status(self) -> X5CameraGetStatusResponse: ...
